# Generated by Django 3.2.6 on 2021-08-19 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_see_borrowers', 'Have spetial page with borrowers'), ('can_tag_books', 'Может помечать сданные книги'))},
        ),
    ]
